branch-defaults:
  master:
    environment: taphr-api-server-dev
global:
  application_name: taphr-api-server
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  profile: eb-cli
  sc: git
